version: '2'         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

exclude_patterns:
- tests/
- migrations/
- migrations_dev/
- migrations_test/
- node_modules/
- '**/lib/'
- .github/
- docker/
- docs/
- web/static/lib/
- web/static/fonts/
# this is only build output
- web/static/css/
- config/
- db/
- dist/
- features/
- '**/node_modules/'
- script/
- '**/spec/'
- '**/test/'
- '**/tests/'
- Tests/
- '**/vendor/'
- '**/*_test.go'
- '**/*.d.ts'

plugins:
  bandit:
    enabled: true
    checks:
      blacklist:
        enabled: false
  eslint:
    enabled: true
  # no developed css in project
  csslint:
    enabled: false
  # disabled as we cannot use the pyproject.toml config from the project/check tox results in gihub action.
  pylint:
    enabled: false
  radon:
    enabled: true
  scss-lint:
    enabled: true
  shell-check:
    enabled: true
  sonar-python:
    enabled: true
    checks:
      python:S125:
        enabled: false
  stylelint:
    enabled: true
