ci:
  autofix_commit_msg: 'chore(pre-commit): autofix run'
  autoupdate_commit_msg: 'chore(pre-commit): autoupdate hooks'

default_install_hook_types:
- pre-commit
- commit-msg

exclude: >
  (?x)(
      migrations/|
      migrations_dev/
  )

repos:
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.0.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: pretty-format-json
    args: [--autofix]
  - id: check-json
    exclude: package-lock.json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    exclude: migrations* | docs*
    additional_dependencies: [toml]
- repo: https://github.com/ambv/black
  rev: 22.8.0
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.17.1
  hooks:
  - id: djlint-jinja
