ci:
  autofix_commit_msg: 'chore(pre-commit): autofix run'
  autoupdate_commit_msg: 'chore(pre-commit): autoupdate hooks'
  autoupdate_branch: dev
  autoupdate_schedule: weekly

default_install_hook_types:
- pre-commit
- commit-msg

exclude: >
  (?x)(
      migrations/|
      migrations_dev/|
      package-lock.jons|
      poetry.lock
  )

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: pretty-format-json
    args: [--autofix]
  - id: check-json
    exclude: package-lock.json
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    exclude: migrations* | docs*
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.19.16
  hooks:
  - id: djlint-jinja
