name: docs

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: christopherpickering/extract-management-2-python39-test
    steps:
    - name: get code
      uses: actions/checkout@v1

    - name: build
      run: tox -e docs

    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
        publish_branch: docs
