name: Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Setup Poetry
      uses: snok/install-poetry@v1
    - name: install deps
      run: |
        sudo sed -i 's/azure\.//' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config build-essential libssl-dev libffi-dev curl git wget libldap2-dev python3-dev python3-pip python3-setuptools unixodbc unixodbc-dev libpq-dev nginx sqlite3 libsqlite3-0 libsasl2-dev libxml2-dev libxmlsec1-dev libxmlsec1-dev redis-server ufw gnupg
        poetry install
    - name: run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.9.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
